apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nq-manager
rules:
- apiGroups:
  - aws.com
  resources:
  - notificationqueues
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
