apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: simpleplane:v1
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: aws-access
          env:
            - name: GROUP
              value: 'aws.com'
            - name: VERSION
              value: 'v1'
            - name: RESOURCE
              value: 'buckets'
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
