apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.aws.com
spec:
  group: aws.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                region:
                  type: string
  scope: Namespaced
  names:
    plural: buckets
    singular: bucket
    kind: Bucket
    shortNames:
      - bkt
